@startuml External Pagination and Filter
title react-agnostic-table external pagination and filter

actor User as user
participant "website" as website
participant "react-agnostic-table" as table
participant "server" as server

user -> website: accesses a table page
website -> server: request page data

activate server
server -> server: get data from database
server -> server: apply business rules
website <-- server: return data for current page and total pages
deactivate server

website -> table: send page data, current page and total pages to package

activate table
website <-- table: return mounted table with data in current page
deactivate table

user <-- website: render page with table component

opt user changes page
    loop
        user -> website: page changes
        website -> table: indicate page change
        website <-- table: trigger page change callback


        website -> server: request new page data

        activate server
        server -> server: get data from database
        server -> server: apply business rules
        website <-- server: return data for current page and total pages
        deactivate server

        website -> table: send new page data, current page and total pages to package
        
        activate table
        website <-- table: return mounted table with new page data
        deactivate table
        user <-- website: shows table with new page data
    end
end

opt user applies a filter on table
    loop
        user -> website: new filter applied
        website -> table: indicate new filter applied
        website <-- table: trigger filter applied callback


        website -> server: request new page data

        activate server
        server -> server: get data from database
        server -> server: apply business rules
        website <-- server: return data for current page and total pages
        deactivate server

        website -> table: send new page data, current page and total pages to package
        
        activate table
        website <-- table: return mounted table with new page data
        deactivate table
        user <-- website: shows table with new page data
    end
end

@enduml